version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0.101-focal-amd64
      - image: 'circleci/mongo:latest'
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: password
      
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            apt-get update && apt-get install -y openjdk-11-jdk
            dotnet tool install --global dotnet-sonarscanner
            dotnet tool install --global coverlet.console            
            echo 'export PATH="$PATH:/root/.dotnet/tools"' >> $BASH_ENV

      - run:
          name: Start Sonarcloud 
          command: |
            dotnet sonarscanner begin \
              /k:"mizrael_OpenSleigh" \
              /o:"mizrael" \
              /d:sonar.host.url="https://sonarcloud.io" \
              /d:sonar.login="$SONAR_TOKEN" \
              /d:sonar.cs.opencover.reportsPaths=/coverage.opencover.xml

      - run:
          name: Build and test          
          command: |
            dotnet restore
            dotnet build --configuration Release --no-restore
            dotnet test --blame --no-restore /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=coverage.opencover.xml     

      - run:
          name: Stop Sonarcloud 
          command: |            
            dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud