version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

jobs:
  build:
    docker:
      - image: cimg/base:2020.01
      - image: mcr.microsoft.com/dotnet/sdk:5.0
      - image: 'circleci/mongo:latest'
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: password

    steps:
      - checkout

      - run:
          name: Build solution
          command: |
            dotnet restore
            dotnet build --configuration Release --no-restore

      - run:
          name: Test
          command: |     
            dotnet test --blame --no-restore /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=coverage.opencover.xml
      
      - sonarcloud/scan

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud