version: 2.1

orbs:
  sonarcloud: ksmc/sonarcloud-dotnet@0.0.29

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
      - image: 'circleci/mongo:latest'
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: password
      
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            apt-get update && apt-get install -y gnupg2

      - sonarcloud/setup-sonar

      - run:
          name: Build and test
          command: |
            dotnet restore
            dotnet build --configuration Release --no-restore
            dotnet test --blame --no-restore /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=coverage.opencover.xml     


workflows:
  main:
    jobs:
      - build:
          context: SonarCloud