version: '3.4'

services:  
  openSleigh.sample11.infrastructure.postgresql:
    container_name: openSleigh.sample11.infrastructure.postgresql    
    image: "postgres:13.4"
    environment:
      POSTGRES_PASSWORD: "Sup3r_p4ssword123"
    ports:
      - 5432:5432     

  openSleigh.sample11.infrastructure.zookeeper:
    image: 'bitnami/zookeeper:3'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    tmpfs: "/datalog"

  openSleigh.sample11.infrastructure.kafka:
    image: 'bitnami/kafka:2'
    restart: always
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment: # https://rmoff.net/2018/08/02/kafka-listeners-explained/
      - KAFKA_LISTENERS=LISTENER_BOB://openSleigh.sample11.infrastructure.kafka:29092,LISTENER_FRED://openSleigh.sample11.infrastructure.kafka:9092
      - KAFKA_ADVERTISED_LISTENERS=LISTENER_BOB://openSleigh.sample11.infrastructure.kafka:29092,LISTENER_FRED://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_BOB:PLAINTEXT,LISTENER_FRED:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=LISTENER_BOB
      - KAFKA_CFG_ZOOKEEPER_CONNECT=openSleigh.sample11.infrastructure.zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - openSleigh.sample11.infrastructure.zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local