name: NuGet Generation

on:
  push:
    branches:
      - nuget
 # pull_request:
#    types: [closed]
 #   branches:
 #     - releases/**

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1        
          
      - name: Generate NuGet packages
        run: |  
          cd src
          dotnet pack -c Release

      - name: Push packages to GitHub registry
        run: dotnet nuget push ./packages/*.nupkg -k ${NUGET_API_KEY} -s https://api.nuget.org/v3/index.json --skip-duplicate
        env:
          NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}        