name: Sonarcloud scan

on:
  push:
  #  paths:
 #   - 'src/**'
 #   - 'tests/**'
 #   branches:
 #     - develop
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
    - 'src/**'
    - 'tests/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:        
        fetch-depth: 0
    - name: Setup .Net SDK (v5.0)
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.100'
    - name: SonarCloud Scan
      uses: highbyte/sonarscan-dotnet@2.0
      with:
        sonarProjectKey: mizrael_OpenSleigh        
        sonarProjectName: OpenSleigh        
        sonarOrganization: mizrael
        dotnetTestArguments: --filter=Category!=Integration --blame --no-restore /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=coverage.opencover.xml
        sonarBeginArguments: /d:sonar.cs.opencover.reportsPaths="**\coverage.opencover.xml"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}