name: Sonarcloud scan

on:
  push:
  #  paths:
 #   - 'src/**'
 #   - 'tests/**'
 #   branches:
 #     - develop
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
    - 'src/**'
    - 'tests/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting for sonarcloud
        fetch-depth: 0
    - name: Setup .Net SDK (v5.0)
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.100'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --filter Category!=Integration --blame --no-restore /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=coverage.opencover.xml
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master    
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}